### ISSUE TITLE
Renaming genomes/chrs within HAL

### ISSUE THREAD

**Issue by joelarmstrong** [ComparativeGenomicsToolkit/coordination#12]
We usually just screw with the .c2h files using sed. But we run into this a whole lot, and it became a blocker for the mouse hub, so it's time to actually do this properly.

- [x] Rename genomes
- [x] Rename chrs

**Comment by diekhans** [comment]
Allowing for multiple names for genomes and sequences would
remove the need to create multiple HALs for each naming scheme.

It seems a bit more complex than just allowing multiple names;
if you come in with `1' or`chr1', you still want the same
sequence back, however when you list sequence you don't
want both `1' and`chr1' back.

I think this requires some type of `naming group' or`naming
paradigm' concept.  For chromosomes, NCBI supports NCBI/Ensembl
names, GenBank accessions, RefSeq accessions, and UCSC-Stype
names.

  ftp://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/All/GCF_000001405.28.assembly.txt

**Comment by joelarmstrong** [comment]
I totally agree, and I think the "naming paradigm" concept would be ideal, but that would require so many changes that I don't think it could happen in the near future.

Personally I think speedups/caching are way more important than avoiding duplicating the HAL for every different naming scheme--space is really really cheap compared to developer time!

**Comment by diekhans** [comment]
We make a separate ticket for multiple names.  We can then
triage as needed

**Comment by ifiddes** [comment]
I am a bit confused by how I would use this tool. Reading the help statement, is this tool capable of renaming sequences, genomes or both? There is a `genome` argument, but then the TSV file talks about existing genome names and new genome names.

 Is the HAL renamed in place or written to stdout?

**Comment by joelarmstrong** [comment]
There's two separate tools for genomes and sequences, but I only remembered to link this issue in the commit for the sequence one.

It's all modified in place. So you should probably back up whatever hal is being modifed, although I did some amount of testing.

 I will try to figure out how to add a tool description to the argument parser HAL uses.

**Comment by joelarmstrong** [comment]
Oh good catch on the help text for the TSV file. I had copy-pasted it from the other utility.

The help text should be a bit better now.
